services:

  go:
    build: ./Go/
    # image: golang:1.22
    container_name: "${COMPOSE_PROJECT_NAME}_go"
    volumes:
      - ../${CODE_GO_DIR}:/app:z
      - .air-temp:/app/tmp
    working_dir: /app
    restart: always
    command: air
    environment:
      - GO111MODULE=on
    networks:
      - front
    ports:
      - "8088:8088"

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${IPRANGE}"
